### ISSUE TITLE
Add and end-to-end test runned by a CI to make sure we can always run an experiment

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/nevergrad#8]
## Target
Make sure we can always run an experiment without error

## Tasks

- [x] add CI
   - [x] add a .g`ithub/workflows/devops-ci.yml` to configure the CI job
   - [x] add a Makefile with instructions to
      - [x] build the venv
      - [x] isntall requirements
      - [x] activate venv and run unit tests
- [x] add a unit test for rice irrigation problem

**Comment by akouete-kpakpo** [comment]
Running `python -m nevergrad.benchmark rice_irrigation --num_workers=6 --plot` is too long to be integrated in a CI

I have to implement a quicker test but even the simple call to 

```python
from nevergrad.functions.irrigation import Irrigation

func = Irrigation(2)
```
is too long. 

I started a profiler and the problem seems to come from the line https://github.com/akouete-kpakpo/nevergrad/blob/e94ba9f0a1ceed9edc2a3d036a3027a933e65cec/nevergrad/functions/irrigation/irrigation.py#L52.

I have to understand why this for loop on 1k samples. Then I can move it to a parameter of the class so that CI would build the function with only 1 sample

**Comment by akouete-kpakpo** [comment]
`make pytest var=nevergrad/functions/irrigation/ mark=ut` to launch unit tests on irrigation
